services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.dev
    environment:
      IG_ENVIRONMENT: dev
      IG_DATABASE_URL: postgresql+psycopg://instagram_bot:instagram_bot@db:5432/instagram_bot
      IG_REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["uvicorn", "app.main:api", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./:/app

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: instagram_bot
      POSTGRES_PASSWORD: instagram_bot
      POSTGRES_DB: instagram_bot
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:
